surname = input("What's your surname? ")
first_name = input("What's your first name? ")
street = input("What is your street name? ")
number = input("What is your number? ")
zip = input("What is your zip code? ")
city = input("What is your city? ")

print(first_name, surname)
print(street, number)
print(zip, city)